enum AuthStatus { AUTHENTICATED, UNAUTHENTICATED }

enum LoginStatus {
  PHONE_VERIFICATION_FAILED,
  SMS_CODE_SENT,
  SMS_CODE_VERIFICATION_FAILED
}

enum UserProfileStatus { NOTCREATED, CREATED, UPDATED, BLOCKED }

enum Gender { MALE, FEMALE, OTHER }
